apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-demo
  namespace: slsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-demo
  template:
    metadata:
      labels:
        app: slsa-demo
    spec:
      containers:
        - name: app
          image: ghcr.io/hodu26/slsa-demo:sha-2d67050227025e871650781615eb6704ac9b9bda
          ports:
            - containerPort: 8080 